### ISSUE TITLE
Make a deny_public_ip_ec2 type SCP

### ISSUE THREAD

**Issue by KevinHock** [ScaleSec/terraform_aws_scp#56]
Maybe something similar to https://github.com/awslabs/aws-config-rules/blob/master/python/EC2_INSTANCE_NO_PUBLIC_IP/EC2_INSTANCE_NO_PUBLIC_IP.py#L60-L63, not sure.

Rationale same as in https://github.com/bridgecrewio/checkov/pull/594

**Comment by jdyke** [comment]
This is an interesting one because there are a lot of ways to make an EC2 public. 

- You can launch it into a default subnet (they will always assign public IPs)
- You can launch it into a non-default subnet with the public IP setting turned on
- You can override subnet settings during deployment with the `run-instances ----associate-public-ip-address` option
- You can associate an Elastic IP with the `allocate-address` command


Outright blocking the IAM permission `iam:AssociateAddress` will more than likely break things like NAT Gateways so that's not a great choice. 

I do see there is an IAM condition `ec2:AssociatePublicIpAddress` which looks like it may be what we want if we specify the resource type to be EC2. I'll have to try a couple different test cases to make sure we limit the blast radius of this SCP and also document what it does NOT cover - if anything.

**Comment by jdyke** [comment]
Related doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-network-iface-embedded.html
